framework:
    messenger:
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default:
                middleware:
                    - PruebaRRHH\Application\Common\Middleware\DomainEventsMiddleware