doctrine:
    dbal:
        driver: 'pdo_pgsql'
        url: '%env(resolve:DATABASE_URL)%'
        charset: UTF8

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            PruebaRRHH:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Domain'
                prefix: 'PruebaRRHH\Domain'
                alias: PruebaRRHH